export type MonthContent = {
  index: number; // 0..11
  name: string;
  theme: string;
  focus: string;
  tips: [string, string];
  prompts: [string, string];
  reflective: string[];
  action: string[];
};

export const MONTHS: MonthContent[] = [
  {
    index: 0,
    name: "January",
    theme: "Reset & Clarity",
    focus: "Clear the noise so your real priorities can breathe.",
    tips: [
      "Write down everything on your mind, then circle the three things that actually matter.",
      "Choose one daily ritual to anchor your morning for the whole month.",
    ],
    prompts: [
      "What am I leaving behind from last year?",
      "What does a clear, calm life look like for me in 2026?",
    ],
    reflective: [
      "I allow myself a clean start without pressure.",
      "I create space to see what truly matters.",
      "I trust clarity to emerge through stillness.",
      "I release what no longer fits my direction.",
      "I am becoming more intentional with my energy.",
      "I allow quiet to guide my next steps.",
      "I trust myself to choose what aligns.",
      "I simplify to make room for clarity.",
      "I move with purpose, not urgency.",
      "I allow my vision to refine naturally.",
      "I trust reflection to sharpen my focus.",
      "I am aligning with what I truly want.",
    ],
    action: [
      "I define clear priorities and act on them daily.",
      "I remove distractions that weaken my focus.",
      "I take ownership of my time and direction.",
      "I follow through on what matters most.",
      "I act with intention, not reaction.",
      "I protect my clarity with firm boundaries.",
      "I decide based on long-term outcomes.",
      "I organize my systems for consistency.",
      "I begin each day with a clear plan.",
      "I act before everything feels perfect.",
      "I stay disciplined on key priorities.",
      "I refine my approach as I progress.",
    ],
  },
  {
    index: 1,
    name: "February",
    theme: "Consistency",
    focus: "Show up the same way on the days you don’t feel like it.",
    tips: [
      "Shrink your habits until they feel almost too easy — then never miss twice.",
      "Track one keystone habit every day; let it carry the rest.",
    ],
    prompts: [
      "Which habit, repeated daily, would change my life this year?",
      "Where am I quietly inconsistent — and why?",
    ],
    reflective: [
      "I trust small actions to create lasting change.",
      "I allow growth through steady repetition.",
      "I build stability by showing up daily.",
      "I am becoming disciplined in my actions.",
      "I trust the process beyond immediate results.",
      "I allow consistency to shape who I am.",
      "I create habits that support my vision.",
      "I develop patience through daily effort.",
      "I trust consistency to build self-respect.",
      "I allow progress to compound over time.",
      "I am becoming dependable to myself.",
      "I trust my ability to stay committed.",
    ],
    action: [
      "I show up regardless of how I feel.",
      "I execute without waiting for motivation.",
      "I honor commitments I make to myself.",
      "I repeat actions that produce results.",
      "I track progress and stay accountable.",
      "I stay consistent even without visible wins.",
      "I remove excuses that interrupt progress.",
      "I maintain structure in my routine.",
      "I finish what I start.",
      "I take ownership of my consistency.",
      "I follow through every day.",
      "I build results through repetition.",
    ],
  },
  {
    index: 2,
    name: "March",
    theme: "Momentum",
    focus: "Build a quiet streak of small wins that pull you forward.",
    tips: [
      "Stack a hard task right after an existing daily habit to ride the momentum.",
      "End each day by choosing tomorrow’s first action — start before motivation arrives.",
    ],
    prompts: [
      "Where is momentum already building in my life?",
      "What’s the smallest next step that would create lift today?",
    ],
    reflective: [
      "I trust the progress already in motion.",
      "I allow effort to carry me forward.",
      "I am becoming more confident in action.",
      "I create energy through movement.",
      "I trust action to build clarity.",
      "I allow progress to expand naturally.",
      "I sustain effort without forcing pace.",
      "I trust myself to keep moving forward.",
      "I build momentum through consistency.",
      "I focus on forward movement.",
      "I strengthen belief through small wins.",
      "I trust effort to create results.",
    ],
    action: [
      "I act quickly instead of overthinking.",
      "I build momentum through completion.",
      "I follow through without delay.",
      "I remove hesitation from my process.",
      "I prioritize progress over perfection.",
      "I execute with speed and clarity.",
      "I maintain daily forward motion.",
      "I take ownership of my pace.",
      "I complete tasks before shifting focus.",
      "I direct energy toward results.",
      "I move forward under any conditions.",
      "I sustain momentum through discipline.",
    ],
  },
  {
    index: 3,
    name: "April",
    theme: "Growth",
    focus: "Lean into the edges where you stretch a little further.",
    tips: [
      "Pick one skill and dedicate 25 focused minutes a day to deliberate practice.",
      "Ask for one piece of honest feedback this month — and act on it.",
    ],
    prompts: [
      "Where am I being called to stretch right now?",
      "What would the next-level version of me do today?",
    ],
    reflective: [
      "I allow growth through every experience.",
      "I trust discomfort to expand me.",
      "I am becoming open to change.",
      "I create space for new perspectives.",
      "I trust my evolution.",
      "I allow growth at a steady pace.",
      "I embrace change with awareness.",
      "I trust each step to build me.",
      "I create opportunities to learn.",
      "I grow stronger through experience.",
      "I allow mistakes to teach me.",
      "I trust my ongoing development.",
    ],
    action: [
      "I pursue growth intentionally.",
      "I apply feedback without resistance.",
      "I step beyond my comfort zone.",
      "I execute habits that expand me.",
      "I invest in valuable skills.",
      "I measure progress honestly.",
      "I take ownership of my development.",
      "I follow through on growth plans.",
      "I build systems for improvement.",
      "I apply lessons immediately.",
      "I stay committed to evolving.",
      "I improve through consistent action.",
    ],
  },
  {
    index: 4,
    name: "May",
    theme: "Balance",
    focus: "Hold ambition and rest in the same hand.",
    tips: [
      "Schedule rest like you schedule meetings — non-negotiable, on the calendar.",
      "End your workday with a clear shutdown ritual to protect your evenings.",
    ],
    prompts: [
      "Where am I out of balance right now?",
      "What would feel restorative this week?",
    ],
    reflective: [
      "I allow balance to guide my energy.",
      "I trust myself to prioritize wisely.",
      "I create space for work and rest.",
      "I am aware of my limits.",
      "I allow rest without guilt.",
      "I trust balance to sustain me.",
      "I create harmony in my routine.",
      "I listen to my needs.",
      "I allow flexibility in my approach.",
      "I trust rest to restore me.",
      "I use time with intention.",
      "I create balance through choice.",
    ],
    action: [
      "I structure my day with intention.",
      "I set boundaries that protect my energy.",
      "I complete priorities without overextending.",
      "I schedule rest deliberately.",
      "I stay present in work, then disconnect.",
      "I manage workload with discipline.",
      "I take ownership of my balance.",
      "I plan my time strategically.",
      "I avoid unnecessary commitments.",
      "I work efficiently to create space.",
      "I protect my well-being daily.",
      "I adjust when balance shifts.",
    ],
  },
  {
    index: 5,
    name: "June",
    theme: "Discipline",
    focus: "Choose what matters over what feels good in the moment.",
    tips: [
      "Decide tonight what tomorrow’s first 90 minutes will look like.",
      "Remove one source of friction or distraction from your environment this week.",
    ],
    prompts: [
      "Where would more discipline give me more freedom?",
      "What am I tolerating that I shouldn’t be?",
    ],
    reflective: [
      "I trust discipline to anchor my actions.",
      "I allow structure to guide me.",
      "I am becoming focused and steady.",
      "I create stability through habits.",
      "I trust myself to follow through.",
      "I allow discipline to support my goals.",
      "I choose effort over comfort.",
      "I trust discipline to build confidence.",
      "I create routines that serve me.",
      "I become more reliable daily.",
      "I allow structure to strengthen me.",
      "I trust consistency over motivation.",
    ],
    action: [
      "I execute regardless of how I feel.",
      "I stay committed to my routine.",
      "I act without delay.",
      "I remove distractions immediately.",
      "I complete what I begin.",
      "I own my results fully.",
      "I maintain daily structure.",
      "I prioritize what matters most.",
      "I stay consistent through resistance.",
      "I repeat disciplined actions daily.",
      "I hold myself accountable.",
      "I execute with precision.",
    ],
  },
  {
    index: 6,
    name: "July",
    theme: "Confidence",
    focus: "Trust the version of you that has done the work.",
    tips: [
      "Keep a running ‘evidence file’ of wins, kind words, and proof of progress.",
      "Speak about yourself the way you’d speak about someone you love.",
    ],
    prompts: [
      "Where would I act differently if I fully trusted myself?",
      "What proof of progress am I overlooking?",
    ],
    reflective: [
      "I trust my ability to handle challenges.",
      "I allow confidence to grow through action.",
      "I am becoming secure in my decisions.",
      "I build confidence through consistency.",
      "I trust myself in uncertainty.",
      "I allow progress to reinforce belief.",
      "I rely on my judgment.",
      "I trust my adaptability.",
      "I create confidence through preparation.",
      "I embrace calculated risks.",
      "I show up fully.",
      "I trust myself to figure things out.",
    ],
    action: [
      "I act decisively.",
      "I follow through with certainty.",
      "I communicate with clarity.",
      "I execute with confidence.",
      "I own my strengths.",
      "I move forward despite doubt.",
      "I take opportunities immediately.",
      "I prepare and perform.",
      "I commit to my decisions.",
      "I trust and act.",
      "I lead with purpose.",
      "I build confidence through action.",
    ],
  },
  {
    index: 7,
    name: "August",
    theme: "Ownership",
    focus: "Take full responsibility for your time, focus and outcomes.",
    tips: [
      "Replace ‘I have to’ with ‘I choose to’ for every commitment this week.",
      "Audit your week: which 20% of activities created 80% of the results?",
    ],
    prompts: [
      "What am I waiting on someone else for that I could own?",
      "Where am I giving my power away?",
    ],
    reflective: [
      "I take responsibility for my path.",
      "I trust myself to lead.",
      "I am accountable for my outcomes.",
      "I create clarity through ownership.",
      "I learn from my mistakes.",
      "I trust my control over my direction.",
      "I accept responsibility without blame.",
      "I grow through accountability.",
      "I trust my decisions.",
      "I lead myself intentionally.",
      "I strengthen through ownership.",
      "I trust accountability to move me forward.",
    ],
    action: [
      "I own every result.",
      "I follow through without excuses.",
      "I accept full responsibility.",
      "I execute with accountability.",
      "I address issues directly.",
      "I stay committed to responsibilities.",
      "I control my schedule.",
      "I hold myself to standards.",
      "I correct mistakes quickly.",
      "I lead through action.",
      "I take initiative.",
      "I complete what I start.",
    ],
  },
  {
    index: 8,
    name: "September",
    theme: "Focus",
    focus: "Do less, but do it with your whole attention.",
    tips: [
      "Single-task in 50-minute blocks; rest in 10. Phone in another room.",
      "Each morning, choose one task that, if done, makes the day a success.",
    ],
    prompts: [
      "What deserves my undivided attention right now?",
      "What am I doing that I should stop?",
    ],
    reflective: [
      "I create space for deep work.",
      "I trust my ability to stay present.",
      "I am becoming more focused daily.",
      "I allow clarity to direct attention.",
      "I trust focus to drive results.",
      "I protect my concentration.",
      "I release distractions easily.",
      "I trust my commitment to priorities.",
      "I engage fully in my work.",
      "I strengthen my attention.",
      "I build structure for focus.",
      "I trust attention to create progress.",
    ],
    action: [
      "I eliminate distractions completely.",
      "I execute with full attention.",
      "I focus on one task.",
      "I follow through without switching.",
      "I protect my time.",
      "I stay aligned all day.",
      "I finish before shifting.",
      "I optimize my environment.",
      "I avoid multitasking.",
      "I execute precisely.",
      "I prioritize effectively.",
      "I produce through focus.",
    ],
  },
  {
    index: 9,
    name: "October",
    theme: "Resilience",
    focus: "Bend, don’t break — and keep moving forward.",
    tips: [
      "When something goes sideways, ask: what’s the next smallest right step?",
      "Build a recovery routine you can rely on on hard days.",
    ],
    prompts: [
      "What has resilience taught me this year?",
      "Where can I be gentler with myself while still moving forward?",
    ],
    reflective: [
      "I trust my ability to recover.",
      "I allow challenges to strengthen me.",
      "I am becoming more resilient.",
      "I build strength through persistence.",
      "I trust setbacks to teach me.",
      "I learn from difficulty.",
      "I adapt under pressure.",
      "I trust my endurance.",
      "I build resilience daily.",
      "I grow stronger through adversity.",
      "I use discomfort to evolve.",
      "I trust myself in hard moments.",
    ],
    action: [
      "I move forward despite obstacles.",
      "I stay committed through difficulty.",
      "I execute under pressure.",
      "I recover and continue quickly.",
      "I act instead of dwelling.",
      "I maintain discipline in setbacks.",
      "I adjust strategy when needed.",
      "I focus on solutions.",
      "I follow through regardless.",
      "I build strength through effort.",
      "I keep progressing.",
      "I execute with determination.",
    ],
  },
  {
    index: 10,
    name: "November",
    theme: "Gratitude",
    focus: "Notice, on purpose, what is already going right.",
    tips: [
      "Each evening, write three specific things you’re grateful for from the day.",
      "Send one short message of appreciation to someone every week.",
    ],
    prompts: [
      "What am I taking for granted that I would deeply miss?",
      "Who has shaped my year — and have I told them?",
    ],
    reflective: [
      "I allow gratitude to shape my mindset.",
      "I trust appreciation to ground me.",
      "I notice what is working.",
      "I create peace through awareness.",
      "I recognize my progress.",
      "I trust gratitude to support growth.",
      "I value small wins.",
      "I create fulfillment through appreciation.",
      "I trust my journey.",
      "I stay present in each moment.",
      "I ground myself in gratitude.",
      "I find contentment in progress.",
    ],
    action: [
      "I build on what is working.",
      "I acknowledge progress daily.",
      "I reflect on achievements.",
      "I maintain a productive mindset.",
      "I use gratitude to stay driven.",
      "I act with appreciation.",
      "I respect my effort.",
      "I build on momentum.",
      "I reinforce positive habits.",
      "I appreciate while advancing.",
      "I act with clarity.",
      "I grow through appreciation.",
    ],
  },
  {
    index: 11,
    name: "December",
    theme: "Reflection",
    focus: "Look back with honesty, forward with intention.",
    tips: [
      "Block 60 quiet minutes to review the year — wins, lessons, and what to repeat.",
      "Choose one word to carry into next year, and write what it means to you.",
    ],
    prompts: [
      "What am I most proud of from this year?",
      "What do I want more of — and less of — in the next?",
    ],
    reflective: [
      "I allow honest reflection.",
      "I trust the lessons I’ve gained.",
      "I recognize my growth.",
      "I create meaning from experience.",
      "I process wins and challenges.",
      "I trust reflection to guide me.",
      "I learn from everything.",
      "I gain clarity by looking back.",
      "I honor my journey.",
      "I become more intentional.",
      "I shape my future through reflection.",
      "I move forward with insight.",
    ],
    action: [
      "I review my progress clearly.",
      "I document key lessons.",
      "I take ownership of results.",
      "I plan from what I learned.",
      "I complete year-end priorities.",
      "I organize for the next phase.",
      "I evaluate performance honestly.",
      "I define next-year goals.",
      "I close tasks with discipline.",
      "I act on insights gained.",
      "I finalize plans with clarity.",
      "I prepare for a strong start.",
    ],
  },
];

export function getMonth(date = new Date()): MonthContent {
  return MONTHS[date.getMonth()];
}

export function getDailyAffirmation(
  style: "reflective" | "action",
  date = new Date(),
): string {
  const month = getMonth(date);
  const pool = style === "action" ? month.action : month.reflective;
  const idx = (date.getDate() - 1) % pool.length;
  return pool[idx];
}